DROP TABLE IF EXISTS names;
CREATE TABLE names (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255)
);
-- INSERT INTO names VALUES(1, 'Alice');
-- INSERT INTO names VALUES(2, 'Beatrice');
-- INSERT INTO names VALUES(3, 'Clarice');